apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:

    metadata:
      labels:
        app: backend

    spec:

      containers:

      - name: backend

        image: vijaykardak/visitor-backend:v1

        ports:
        - containerPort: 5000

        env:

        - name: DB_HOST
          value: mariadb

        - name: DB_USER
          value: root

        - name: DB_PASSWORD
          value: root

        - name: DB_NAME
          value: devopsdb
